-- ============================================================================
-- SCRIPT DE PROSPECÇÃO: tabelas novas e ajuste na tabela de marcas
-- ============================================================================
-- Este script NÃO apaga nada. Ele só acrescenta colunas e cria tabelas novas.
-- Pode rodar mais de uma vez sem problema (por isso o "if not exists").
--
-- Onde rodar: painel do Supabase > seu projeto > SQL Editor > New query
-- Cole tudo isto e clique em "Run".
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Coluna nova na tabela "marcas": marcar quais você selecionou pra enviar
-- ----------------------------------------------------------------------------
alter table marcas
  add column if not exists selecionada boolean not null default false;

-- Coluna nova: quando a marca recebeu o e-mail de prospecção (fica vazia até enviar)
alter table marcas
  add column if not exists prospeccao_enviada_em timestamptz;


-- ----------------------------------------------------------------------------
-- 2. Tabela nova: email_envios
--    Uma linha por e-mail enviado, pra você saber exatamente quem recebeu.
-- ----------------------------------------------------------------------------
create table if not exists email_envios (
  id bigint generated by default as identity primary key,
  email text not null,
  assunto text not null,
  status text not null check (status in ('ok', 'erro')),
  erro text,
  resend_id text,
  criado_em timestamptz not null default now()
);

alter table email_envios enable row level security;

drop policy if exists "logada le envios" on email_envios;
create policy "logada le envios"
  on email_envios for select
  using (auth.role() = 'authenticated');

drop policy if exists "logada grava envios" on email_envios;
create policy "logada grava envios"
  on email_envios for insert
  with check (auth.role() = 'authenticated');


-- ----------------------------------------------------------------------------
-- 3. Tabela nova: email_optout
--    Quem pediu pra sair (respondeu SAIR). Nunca mais recebe.
-- ----------------------------------------------------------------------------
create table if not exists email_optout (
  id bigint generated by default as identity primary key,
  email text not null unique,
  criado_em timestamptz not null default now()
);

alter table email_optout enable row level security;

drop policy if exists "logada le optout" on email_optout;
create policy "logada le optout"
  on email_optout for select
  using (auth.role() = 'authenticated');

drop policy if exists "logada grava optout" on email_optout;
create policy "logada grava optout"
  on email_optout for insert
  with check (auth.role() = 'authenticated');


-- ============================================================================
-- FIM. Depois de rodar, me avisa que eu sigo pro próximo passo.
-- ============================================================================
